# File: roles/lighttpd/tasks/main.yml
---

- name: Install the lighttpd package.
  ansible.builtin.apt:
    pkg:
    - lighttpd

- name: Upload a sample testpage.
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart lighttpd
