# File: dns.yml
---
- name: Install NS
  hosts: nameservers
  remote_user: root
  roles:
    - bind9
    - ufw

- name: Install LB
  hosts: loadbalancers
  remote_user: root
  roles:
    - haproxy
    - ufw
