# File: roles/bind9/tasks/main.yml
---

- name: Install the Bind9 packages.
  ansible.builtin.apt:
    pkg:
    - bind9
    - bind9utils
    - bind9-doc
    - dnsutils
    
- name: Upload a sample zonefile.
  ansible.builtin.template:
    src: templates/cq.fi.j2
    dest: /etc/bind/db.cq.fi
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart bind9
